
import csv

# Full Manual Data (1-150 combined and cleaned)
quiz_data = [
    # Part 1 (1-30)
    {"문장": "El tren sale ( ) Madrid a las ocho.", "정답": "para", "오답": "por,de,en,hacia", "번역": "기차는 8시에 마드리드*행*이다 (마드리드를 향해 출발한다).", "유형": "loc_direction", "해설": "'salir para'는 목적지를 강조하여 '~행이다'를 의미합니다."},
    {"문장": "Hemos caminado ( ) el bosque durante dos horas.", "정답": "por", "오답": "para,a,de,en", "번역": "우리는 2시간 동안 숲*을 지나* 걸었다.", "유형": "loc_path", "해설": "장소를 통과하거나 경유하는 이동은 'por'입니다."},
    {"문장": "La reunión está programada ( ) el próximo lunes.", "정답": "para", "오답": "por,a,de,en", "번역": "회의는 다음 주 월요일*로* 예정되어 있다.", "유형": "time_deadline", "해설": "예정된 기한은 'para'입니다."},
    {"문장": "El regalo es ( ) mi madre.", "정답": "para", "오답": "por,a,de,con", "번역": "이 선물은 나의 어머니*를 위한* 것이다.", "유형": "company", "해설": "수혜자는 'para'입니다."},
    {"문장": "No puedo dormir ( ) el ruido de la calle.", "정답": "por", "오답": "para,de,a,sin", "번역": "거리의 소음 *때문에* 잠을 잘 수가 없다.", "유형": "cause", "해설": "원인(~때문에)은 'por'입니다."},
    {"문장": "El libro está ( ) la mesa.", "정답": "sobre", "오답": "bajo,entre,hacia,desde", "번역": "책은 탁자 *위에* 있다.", "유형": "loc_position", "해설": "표면 위는 'sobre'입니다."},
    {"문장": "Llegaremos ( ) las cinco de la tarde.", "정답": "hacia", "오답": "hasta,desde,de,entre", "번역": "우리는 오후 5시 *무렵에* 도착할 것이다.", "유형": "time_point", "해설": "대략적인 시간은 'hacia'입니다."},
    {"문장": "Voy a viajar ( ) avión.", "정답": "en", "오답": "por,a,con,de", "번역": "나는 비행기*를 타고* 여행할 것이다.", "유형": "method", "해설": "교통 수단은 'en'입니다."},
    {"문장": "Este cuadro fue pintado ( ) Picasso.", "정답": "por", "오답": "para,de,a,con", "번역": "이 그림은 피카소*에 의해* 그려졌다.", "유형": "method", "해설": "수동태의 행위자는 'por'입니다."},
    {"문장": "Salimos ( ) casa muy temprano.", "정답": "de", "오답": "a,en,por,para", "번역": "우리는 집*에서* 매우 일찍 나왔다.", "유형": "loc_origin", "해설": "출발지는 'de'입니다."},
    {"문장": "La farmacia está ( ) el banco y el supermercado.", "정답": "entre", "오답": "sobre,bajo,ante,tras", "번역": "약국은 은행과 슈퍼마켓 *사이에* 있다.", "유형": "loc_position", "해설": "사이는 'entre'입니다."},
    {"문장": "Estudio español ( ) mejorar mi trabajo.", "정답": "para", "오답": "por,a,de,en", "번역": "나는 업무 능력을 향상시키기 *위해* 스페인어를 공부한다.", "유형": "purpose", "해설": "목적은 'para'입니다."},
    {"문장": "Hablamos ( ) la situación económica.", "정답": "sobre", "오답": "en,con,por,para", "번역": "우리는 경제 상황*에 대해* 이야기했다.", "유형": "topic", "해설": "주제는 'sobre'입니다."},
    {"문장": "El gato se escondió ( ) la cama.", "정답": "bajo", "오답": "sobre,en,a,de", "번역": "고양이는 침대 *밑에* 숨었다.", "유형": "loc_position", "해설": "아래는 'bajo'입니다."},
    {"문장": "Te llamaré ( ) las diez y las once.", "정답": "entre", "오답": "a,de,por,hacia", "번역": "10시와 11시 *사이에* 전화할게.", "유형": "time_duration", "해설": "시간 사이는 'entre'입니다."},
    {"문장": "No puedo vivir ( ) ti.", "정답": "sin", "오답": "con,por,para,de", "번역": "나는 너 *없이* 살 수 없다.", "유형": "company", "해설": "부재는 'sin'입니다."},
    {"문장": "Prefiero pagar ( ) tarjeta.", "정답": "con", "오답": "por,a,en,de", "번역": "나는 카드*로* 결제하는 것을 선호한다.", "유형": "method", "해설": "도구/수단은 'con'입니다."},
    {"문장": "Estuvimos en la fiesta ( ) el amanecer.", "정답": "hasta", "오답": "hacia,desde,por,para", "번역": "우리는 새벽*까지* 파티에 있었다.", "유형": "time_deadline", "해설": "종료 시점은 'hasta'입니다."},
    {"문장": "Vivo en España ( ) 2015.", "정답": "desde", "오답": "de,en,a,hasta", "번역": "나는 2015년*부터* 스페인에 살고 있다.", "유형": "time_point", "해설": "기점은 'desde'입니다."},
    {"문장": "El niño se escondió ( ) la puerta.", "정답": "tras", "오답": "ante,bajo,sobre,entre", "번역": "아이는 문 *뒤에* 숨었다.", "유형": "loc_position", "해설": "뒤는 'tras'입니다."},
    {"문장": "Luchamos ( ) la injusticia.", "정답": "contra", "오답": "por,para,con,de", "번역": "우리는 불의*에 맞서* 싸운다.", "유형": "topic", "해설": "반대는 'contra'입니다."},
    {"문장": "Lo hice ( ) ayudar, no por interés.", "정답": "para", "오답": "por,a,de,en", "번역": "나는 돕기 *위해* 그것을 했다.", "유형": "purpose", "해설": "목적은 'para'입니다."},
    {"문장": "Cambié mi coche viejo ( ) uno nuevo.", "정답": "por", "오답": "para,a,con,de", "번역": "나는 내 헌 차를 새 차*와* 바꿨다.", "유형": "exchange", "해설": "교환은 'por'입니다."},
    {"문장": "El tren pasa ( ) un túnel muy largo.", "정답": "por", "오답": "para,a,de,en", "번역": "기차는 매우 긴 터널*을 통과해* 지나간다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "Estoy ( ) vacaciones.", "정답": "de", "오답": "en,a,por,para", "번역": "나는 휴가 *중*이다.", "유형": "manner", "해설": "상태는 'de'입니다."},
    {"문장": "Vengo ( ) trabajar.", "정답": "de", "오답": "a,en,por,para", "번역": "나는 일하*고 나서* (일터에서) 오는 길이다.", "유형": "loc_origin", "해설": "출발지는 'de'입니다."},
    {"문장": "El museo está ( ) la derecha.", "정답": "a",
     "오답": "en,de,por,para",
     "번역": "박물관은 오른쪽*에* 있다.",
     "유형": "loc_position",
     "해설": "방향 위치는 'a'입니다."},
    {"문장": "Trabajo ( ) lunes a viernes.",
     "정답": "de",
     "오답": "a,en,por,para",
     "번역": "나는 월요일*부터* 금요일까지 일한다.",
     "유형": "time_duration",
     "해설": "시작점은 'de'입니다."},
    {"문장": "Voy a casa ( ) pie.",
     "정답": "a",
     "오답": "en,por,con,de",
     "번역": "나는 *걸어서* 집에 간다.",
     "유형": "method",
     "해설": "걸어서는 'a pie'입니다."},
    {"문장": "Gracias ( ) todo.",
     "정답": "por",
     "오답": "para,a,de,con",
     "번역": "모든 것에 *대해* 고마워.",
     "유형": "cause",
     "해설": "감사의 이유는 'por'입니다."},

    # Part 2 (31-60)
    {"문장": "No hables ( ) la clase.", "정답": "durante", "오답": "por,para,entre,hacia", "번역": "수업 *중에* (동안) 말하지 마라.", "유형": "time_duration", "해설": "기간 동안은 'durante'입니다."},
    {"문장": "( ) mi opinión, eso no es correcto.", "정답": "según", "오답": "por,para,con,de", "번역": "내 의견*에 따르면*, 그것은 옳지 않다.", "유형": "topic", "해설": "출처는 'según'입니다."},
    {"문장": "El ladrón entró ( ) la ventana.", "정답": "por", "오답": "para,a,de,en", "번역": "도둑은 창문*을 통해* 들어왔다.", "유형": "loc_path", "해설": "통과는 'por'입니다."},
    {"문장": "Estoy muy cansado ( ) tanto trabajar.", "정답": "de", "오답": "a,en,con,sin", "번역": "나는 너무 많이 일*해서* 피곤하다.", "유형": "cause", "해설": "원인은 'de'입니다."},
    {"문장": "El libro trata ( ) la historia de España.", "정답": "sobre", "오답": "en,con,por,para", "번역": "그 책은 스페인 역사*에 대해* 다룬다.", "유형": "topic", "해설": "주제는 'sobre'입니다."},
    {"문장": "Vamos a la playa ( ) coche.", "정답": "en", "오답": "a,por,con,de", "번역": "우리는 차*를 타고* 해변에 간다.", "유형": "method", "해설": "교통수단은 'en'입니다."},
    {"문장": "Este regalo es ( ) mi novia.", "정답": "para", "오답": "por,a,de,con", "번역": "이 선물은 내 여자친구*를 위한* 것이다.", "유형": "company", "해설": "수혜자는 'para'입니다."},
    {"문장": "( ) fin ha dejado de llover.", "정답": "por", "오답": "para,a,de,en", "번역": "*마침내* 비가 그쳤다.", "유형": "manner", "해설": "'Por fin'은 관용구입니다."},
    {"문장": "Vivo ( ) mis padres.", "정답": "con", "오답": "sin,por,para,de", "번역": "나는 부모님*과 함께* 산다.", "유형": "company", "해설": "동반은 'con'입니다."},
    {"문장": "No salgas ( ) abrigo.", "정답": "sin", "오답": "con,por,para,de", "번역": "코트 *없이* 나가지 마라.", "유형": "company", "해설": "부재는 'sin'입니다."},
    {"문장": "El avión vuela ( ) las nubes.", "정답": "sobre", "오답": "bajo,entre,hacia,desde", "번역": "비행기가 구름 *위로* 날고 있다.", "유형": "loc_position", "해설": "위는 'sobre'입니다."},
    {"문장": "Caminamos ( ) la playa al atardecer.", "정답": "por", "오답": "para,a,de,en", "번역": "우리는 해변*을* (따라) 걸었다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "La clase termina ( ) las dos.", "정답": "a", "오답": "en,de,por,para", "번역": "수업은 2시*에* 끝난다.", "유형": "time_point", "해설": "시각은 'a'입니다."},
    {"문장": "Estoy ( ) vacaciones.", "정답": "de", "오답": "en,a,por,para", "번역": "나는 휴가 *중*이다.", "유형": "manner", "해설": "상태는 'de'입니다."},
    {"문장": "Lo hice ( ) error.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 그것을 실수*로* 했다.", "유형": "cause", "해설": "이유는 'por'입니다."},
    {"문장": "Este tren va ( ) París.", "정답": "hacia", "오답": "por,de,en,con", "번역": "이 기차는 파리 *쪽으로* 간다.", "유형": "loc_direction", "해설": "방향은 'hacia'입니다."},
    {"문장": "Trabajo ( ) ocho a cinco.", "정답": "de", "오답": "a,en,por,para", "번역": "나는 8시*부터* 5시까지 일한다.", "유형": "time_duration", "해설": "시작점은 'de'입니다."},
    {"문장": "El gato está ( ) la mesa.", "정답": "debajo de", "오답": "encima de,al lado de,cerca de,lejos de", "번역": "고양이는 탁자 *아래에* 있다.", "유형": "loc_position", "해설": "아래는 'debajo de'입니다."},
    {"문장": "Mi casa está ( ) la escuela.", "정답": "cerca de", "오답": "lejos de,entre,sobre,bajo", "번역": "우리 집은 학교 *근처에* 있다.", "유형": "loc_position", "해설": "근처는 'cerca de'입니다."},
    {"문장": "( ) pesar de la lluvia, salimos.", "정답": "A", "오답": "De,En,Por,Con", "번역": "비*에도* 불구하고 우리는 나갔다.", "유형": "cause", "해설": "양보는 'A pesar de'입니다."},
    {"문장": "Llámame ( ) de llegar.", "정답": "antes", "오답": "después,durante,mientras,hasta", "번역": "도착하기 *전에* 전화해라.", "유형": "time_point", "해설": "전은 'antes de'입니다."},
    {"문장": "El vaso es ( ) cristal.", "정답": "de", "오답": "en,con,por,para", "번역": "그 컵은 유리*로* 만들어졌다.", "유형": "material", "해설": "재료는 'de'입니다."},
    {"문장": "Voy a estar aquí ( ) el lunes.", "정답": "hasta", "오답": "desde,de,a,en", "번역": "나는 월요일*까지* 여기에 있을 것이다.", "유형": "time_deadline", "해설": "종료 시점은 'hasta'입니다."},
    {"문장": "Estudio español ( ) viajar a México.", "정답": "para", "오답": "por,a,de,en", "번역": "나는 멕시코를 여행하기 *위해* 스페인어를 공부한다.", "유형": "purpose", "해설": "목적은 'para'입니다."},
    {"문장": "La carta fue escrita ( ) María.", "정답": "por", "오답": "para,de,a,con", "번역": "그 편지는 마리아*에 의해* 쓰여졌다.", "유형": "method", "해설": "행위자는 'por'입니다."},
    {"문장": "Estamos ( ) contra de la guerra.", "정답": "en", "오답": "a,de,por,para", "번역": "우리는 전쟁에 *반대*한다.", "유형": "topic", "해설": "반대는 'en contra de'입니다."},
    {"문장": "Salgo ( ) casa a las ocho.", "정답": "de", "오답": "a,en,por,para", "번역": "나는 8시에 집*에서* 나온다.", "유형": "loc_origin", "해설": "출발지는 'de'입니다."},
    {"문장": "Hay un parque ( ) mi casa.", "정답": "frente a", "오답": "junto a,lejos de,dentro de,sobre", "번역": "우리 집 *맞은편에* 공원이 있다.", "유형": "loc_position", "해설": "맞은편은 'frente a'입니다."},
    {"문장": "Te cambio mi libro ( ) el tuyo.", "정답": "por", "오답": "para,a,de,con", "번역": "내 책을 네 것*과* 바꿀게.", "유형": "exchange", "해설": "교환은 'por'입니다."},
    {"문장": "Nos vemos ( ) la tarde.", "정답": "por", "오답": "a,de,en,para", "번역": "오후*에* 보자.", "유형": "time_duration", "해설": "시간대는 'por'입니다."},

    # Part 3 (61-90)
    {"문장": "El coche está aparcado ( ) la casa.", "정답": "delante de", "오답": "detrás de,dentro de,lejos de,sobre", "번역": "차는 집 *앞에* 주차되어 있다.", "유형": "loc_position", "해설": "앞은 'delante de'입니다."},
    {"문장": "Hay un jardín ( ) la escuela.", "정답": "detrás de", "오답": "delante de,encima de,debajo de,entre", "번역": "학교 *뒤에* 정원이 있다.", "유형": "loc_position", "해설": "뒤는 'detrás de'입니다."},
    {"문장": "Las llaves están ( ) el bolso.", "정답": "dentro de", "오답": "fuera de,encima de,debajo de,junto a", "번역": "열쇠는 가방 *안에* 있다.", "유형": "loc_position", "해설": "안은 'dentro de'입니다."},
    {"문장": "Estamos esperando ( ) la oficina.", "정답": "fuera de", "오답": "dentro de,sobre,bajo,entre", "번역": "우리는 사무실 *밖에서* 기다리고 있다.", "유형": "loc_position", "해설": "밖은 'fuera de'입니다."},
    {"문장": "Aprobé el examen ( ) tu ayuda.", "정답": "gracias a", "오답": "a causa de,por,para,sin", "번역": "네 도움 *덕분에* 시험에 합격했다.", "유형": "cause", "해설": "덕분에는 'gracias a'입니다."},
    {"문장": "No fuimos al parque ( ) la lluvia.", "정답": "a causa de", "오답": "gracias a,para,con,sin", "번역": "비 *때문에* 공원에 가지 않았다.", "유형": "cause", "해설": "때문에는 'a causa de'입니다."},
    {"문장": "El gato saltó ( ) la valla.", "정답": "sobre", "오답": "bajo,entre,hacia,desde", "번역": "고양이는 울타리 *위로* 뛰어넘었다.", "유형": "loc_direction", "해설": "위로는 'sobre'입니다."},
    {"문장": "Caminamos ( ) la orilla del río.", "정답": "por", "오답": "para,a,de,en", "번역": "우리는 강변*을 따라* 걸었다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "La tienda está ( ) la izquierda.", "정답": "a", "오답": "en,de,por,para", "번역": "가게는 왼쪽*에* 있다.", "유형": "loc_position", "해설": "방향 위치는 'a'입니다."},
    {"문장": "Trabajo ( ) lunes a viernes.", "정답": "de", "오답": "a,en,por,para", "번역": "월요일*부터* 금요일까지 일한다.", "유형": "time_duration", "해설": "시작점은 'de'입니다."},
    {"문장": "Voy ( ) médico.", "정답": "al", "오답": "del,en el,por el,para el", "번역": "나는 병원(의사)*에* 간다.", "유형": "loc_direction", "해설": "'a'+'el' = 'al'입니다."},
    {"문장": "Vengo ( ) cine.", "정답": "del", "오답": "al,en el,por el,para el", "번역": "나는 영화관*에서* 오는 길이다.", "유형": "loc_origin", "해설": "'de'+'el' = 'del'입니다."},
    {"문장": "El libro es ( ) mi hermano.", "정답": "de", "오답": "a,en,por,para", "번역": "그 책은 내 형*의* 것이다.", "유형": "company", "해설": "소유는 'de'입니다."},
    {"문장": "Hablamos ( ) teléfono.", "정답": "por", "오답": "en,a,de,con", "번역": "우리는 전화*로* 이야기한다.", "유형": "method", "해설": "수단은 'por'입니다."},
    {"문장": "Escribo ( ) lápiz.", "정답": "con", "오답": "en,por,a,de", "번역": "나는 연필*로* 쓴다.", "유형": "method", "해설": "도구는 'con'입니다."},
    {"문장": "Voy a estar aquí ( ) una semana.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 일주일 *동안* 여기에 있을 것이다.", "유형": "time_duration", "해설": "기간은 'por'입니다."},
    {"문장": "La tarea es ( ) mañana.", "정답": "para", "오답": "por,a,de,en", "번역": "숙제는 내일*까지*다.", "유형": "time_deadline", "해설": "기한은 'para'입니다."},
    {"문장": "El tren pasa ( ) un puente.", "정답": "por", "오답": "para,a,de,en", "번역": "기차는 다리*를 지나* 간다.", "유형": "loc_path", "해설": "통과는 'por'입니다."},
    {"문장": "Estoy ( ) acuerdo contigo.", "정답": "de", "오답": "en,a,por,para", "번역": "나는 너에게 *동의한다*.", "유형": "manner", "해설": "'Estar de acuerdo'는 숙어입니다."},
    {"문장": "Lo compré ( ) diez euros.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 그것을 10유로*에* 샀다.", "유형": "exchange", "해설": "가격/교환은 'por'입니다."},
    {"문장": "Este autobús es ( ) Madrid.", "정답": "para", "오답": "por,a,de,en", "번역": "이 버스는 마드리드*행*이다.", "유형": "loc_direction", "해설": "목적지는 'para'입니다."},
    {"문장": "El niño se escondió ( ) la mesa.", "정답": "debajo de", "오답": "encima de,sobre,entre,hacia", "번역": "아이는 탁자 *밑에* 숨었다.", "유형": "loc_position", "해설": "아래는 'debajo de'입니다."},
    {"문장": "La lámpara está ( ) la mesa.", "정답": "encima de", "오답": "debajo de,bajo,entre,hacia", "번역": "램프는 탁자 *위에* 있다.", "유형": "loc_position", "해설": "위는 'encima de'입니다."},
    {"문장": "Vivo ( ) mis abuelos.", "정답": "con", "오답": "sin,por,para,de", "번역": "나는 조부모님*과 함께* 산다.", "유형": "company", "해설": "동반은 'con'입니다."},
    {"문장": "No puedo hacerlo ( ) ti.", "정답": "sin", "오답": "con,por,para,de", "번역": "너 *없이는* 그것을 할 수 없다.", "유형": "company", "해설": "결핍은 'sin'입니다."},
    {"문장": "Llegaremos ( ) las tres.", "정답": "a", "오답": "en,de,por,para", "번역": "우리는 3시*에* 도착할 것이다.", "유형": "time_point", "해설": "시각은 'a'입니다."},
    {"문장": "Salimos ( ) viaje mañana.", "정답": "de", "오답": "en,a,por,para", "번역": "우리는 내일 여행을 *떠난다*.", "유형": "manner", "해설": "'Salir de viaje'는 숙어입니다."},
    {"문장": "El cuadro está colgado ( ) la pared.", "정답": "en", "오답": "a,de,por,para", "번역": "그림은 벽*에* 걸려 있다.", "유형": "loc_position", "해설": "표면 위치는 'en'입니다."},
    {"문장": "Voy ( ) pie.", "정답": "a", "오답": "en,por,con,de", "번역": "나는 *걸어서* 간다.", "유형": "method", "해설": "걸어서는 'a pie'입니다."},
    {"문장": "Lo hice ( ) amor.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 사랑 *때문에* 그것을 했다.", "유형": "cause", "해설": "원인은 'por'입니다."},

    # Part 4 (91-120)
    {"문장": "Hay un jardín ( ) la casa.", "정답": "alrededor de", "오답": "dentro de,sobre,bajo,entre", "번역": "집 *주위에* 정원이 있다.", "유형": "loc_position", "해설": "주변은 'alrededor de'입니다."},
    {"문장": "Lávate las manos ( ) comer.", "정답": "antes de", "오답": "después de,durante,mientras,hasta", "번역": "밥 먹기 *전에* 손을 씻어라.", "유형": "time_point", "해설": "전은 'antes de'입니다."},
    {"문장": "Iremos al cine ( ) cenar.", "정답": "después de", "오답": "antes de,durante,hasta,desde", "번역": "저녁 먹은 *후에* 영화관에 갈 것이다.", "유형": "time_point", "해설": "후는 'después de'입니다."},
    {"문장": "El banco está ( ) la plaza.", "정답": "frente a", "오답": "dentro de,sobre,bajo,entre", "번역": "은행은 광장 *맞은편에* 있다.", "유형": "loc_position", "해설": "맞은편은 'frente a'입니다."},
    {"문장": "( ) este tema, no tengo nada que decir.", "정답": "En cuanto a", "오답": "A pesar de,Debido a,Gracias a,Junto a", "번역": "이 주제*에 관해서는*, 할 말이 없다.", "유형": "topic", "해설": "관해서는 'En cuanto a'입니다."},
    {"문장": "La farmacia está ( ) el supermercado.", "정답": "junto a", "오답": "lejos de,dentro de,sobre,bajo", "번역": "약국은 슈퍼마켓 *바로 옆에* 있다.", "유형": "loc_position", "해설": "옆은 'junto a'입니다."},
    {"문장": "No pudimos salir ( ) la nieve.", "정답": "debido a", "오답": "gracias a,para,con,sin", "번역": "눈 *때문에* 나갈 수 없었다.", "유형": "cause", "해설": "때문에는 'debido a'입니다."},
    {"문장": "( ) ser tan joven, es muy maduro.", "정답": "A pesar de", "오답": "Debido a,Gracias a,Junto a,Frente a", "번역": "그렇게 어린 *것에도 불구하고*, 그는 매우 성숙하다.", "유형": "cause", "해설": "불구하고는 'A pesar de'입니다."},
    {"문장": "Te enviaré la información ( ) correo electrónico.", "정답": "vía", "오답": "en,a,de,con", "번역": "이메일 *편으로* 정보를 보내주겠다.", "유형": "method", "해설": "수단은 'vía'입니다."},
    {"문장": "Todos vinieron ( ) Juan.", "정답": "excepto", "오답": "con,para,por,de", "번역": "후안을 *제외하고* 모두 왔다.", "유형": "company", "해설": "제외는 'excepto'입니다."},
    {"문장": "Se resolvió el problema ( ) el diálogo.", "정답": "mediante", "오답": "durante,hacia,hasta,desde", "번역": "문제는 대화를 *통해* 해결되었다.", "유형": "method", "해설": "수단은 'mediante'입니다."},
    {"문장": "La lluvia continuó ( ) toda la noche.", "정답": "durante", "오답": "entre,hacia,hasta,desde", "번역": "비는 밤새 *내내* 계속되었다.", "유형": "time_duration", "해설": "기간은 'durante'입니다."},
    {"문장": "El precio varía ( ) el tamaño.", "정답": "según", "오답": "por,para,con,de", "번역": "가격은 크기*에 따라* 다르다.", "유형": "manner", "해설": "따라는 'según'입니다."},
    {"문장": "La luz entra ( ) la ventana.", "정답": "a través de", "오답": "encima de,debajo de,junto a,frente a", "번역": "빛이 창문*을 통해* 들어온다.", "유형": "loc_path", "해설": "통과는 'a través de'입니다."},
    {"문장": "Quiero té ( ) café.", "정답": "en vez de", "오답": "a causa de,gracias a,junto a,frente a", "번역": "커피 *대신에* 차를 원한다.", "유형": "exchange", "해설": "대신에는 'en vez de'입니다."},
    {"문장": "El gato está ( ) la silla.", "정답": "bajo", "오답": "sobre,entre,hacia,desde", "번역": "고양이는 의자 *밑에* 있다.", "유형": "loc_position", "해설": "아래는 'bajo'입니다."},
    {"문장": "El libro está ( ) la estantería.", "정답": "en", "오답": "a,de,por,para", "번역": "책은 책장*에* 있다.", "유형": "loc_position", "해설": "위치는 'en'입니다."},
    {"문장": "Voy ( ) Madrid mañana.", "정답": "a", "오답": "de,en,por,con", "번역": "나는 내일 마드리드*로* 간다.", "유형": "loc_direction", "해설": "목적지는 'a'입니다."},
    {"문장": "Este regalo es ( ) ti.", "정답": "para", "오답": "por,a,de,en", "번역": "이 선물은 너*를 위한* 것이다.", "유형": "company", "해설": "수혜자는 'para'입니다."},
    {"문장": "Lo hice ( ) ti.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 너 *때문에* 그것을 했다.", "유형": "cause", "해설": "원인은 'por'입니다."},
    {"문장": "Hablamos ( ) política.", "정답": "de", "오답": "a,en,por,para", "번역": "우리는 정치*에 대해* 이야기했다.", "유형": "topic", "해설": "주제는 'de'입니다."},
    {"문장": "El tren sale ( ) las cinco.", "정답": "a", "오답": "en,de,por,para", "번역": "기차는 5시*에* 출발한다.", "유형": "time_point", "해설": "시각은 'a'입니다."},
    {"문장": "Vivo ( ) Corea.", "정답": "en", "오답": "a,de,por,para", "번역": "나는 한국*에* 산다.", "유형": "loc_position", "해설": "장소는 'en'입니다."},
    {"문장": "Soy ( ) España.", "정답": "de", "오답": "a,en,por,para", "번역": "나는 스페인 *출신*이다.", "유형": "loc_origin", "해설": "출신은 'de'입니다."},
    {"문장": "Voy ( ) casa.", "정답": "a", "오답": "en,de,por,para", "번역": "나는 집*으로* 간다.", "유형": "loc_direction", "해설": "목적지는 'a'입니다."},
    {"문장": "La carta es ( ) Juan.", "정답": "para", "오답": "por,a,de,en", "번역": "편지는 후안*에게* 이다.", "유형": "company", "해설": "수신인은 'para'입니다."},
    {"문장": "Gracias ( ) venir.", "정답": "por", "오답": "para,a,de,en", "번역": "와줘서 *고마워*.", "유형": "cause", "해설": "이유는 'por'입니다."},
    {"문장": "Estudio ( ) aprender.", "정답": "para", "오답": "por,a,de,en", "번역": "나는 배우기 *위해* 공부한다.", "유형": "purpose", "해설": "목적은 'para'입니다."},
    {"문장": "Caminamos ( ) el parque.", "정답": "por", "오답": "para,a,de,en", "번역": "우리는 공원*을* 걷는다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "El libro está ( ) la mesa.", "정답": "sobre", "오답": "bajo,entre,hacia,desde", "번역": "책은 탁자 *위에* 있다.", "유형": "loc_position", "해설": "위는 'sobre'입니다."},

    # Part 5 (121-150)
    {"문장": "Estoy ( ) contra de la violencia.", "정답": "en", "오답": "a,de,por,para", "번역": "나는 폭력에 *반대*한다.", "유형": "topic", "해설": "숙어는 'estar en contra de'입니다."},
    {"문장": "Luchamos ( ) el enemigo.", "정답": "contra", "오답": "por,para,con,de", "번역": "우리는 적*과 싸운다*.", "유형": "topic", "해설": "대항은 'contra'입니다."},
    {"문장": "Voy a la escuela ( ) autobús.", "정답": "en", "오답": "a,por,con,de", "번역": "나는 버스*로* 학교에 간다.", "유형": "method", "해설": "교통수단은 'en'입니다."},
    {"문장": "Corta el pan ( ) el cuchillo.", "정답": "con", "오답": "en,por,a,de", "번역": "칼*로* 빵을 잘라라.", "유형": "method", "해설": "도구는 'con'입니다."},
    {"문장": "No puedo ver ( ) las gafas.", "정답": "sin", "오답": "con,por,para,de", "번역": "안경 *없이는* 볼 수가 없다.", "유형": "company", "해설": "결핍은 'sin'입니다."},
    {"문장": "Te esperaré ( ) las seis.", "정답": "hasta", "오답": "desde,de,a,en", "번역": "6시*까지* 기다릴게.", "유형": "time_deadline", "해설": "종료는 'hasta'입니다."},
    {"문장": "Estudio ( ) las ocho de la mañana.", "정답": "desde", "오답": "hasta,de,a,en", "번역": "아침 8시*부터* 공부하고 있다.", "유형": "time_point", "해설": "시작점은 'desde'입니다."},
    {"문장": "El avión sale ( ) Nueva York.", "정답": "para", "오답": "por,a,de,en", "번역": "비행기는 뉴욕*행*이다.", "유형": "loc_direction", "해설": "목적지는 'para'입니다."},
    {"문장": "Paseamos ( ) el jardín.", "정답": "por", "오답": "para,a,de,en", "번역": "우리는 정원*을* 산책한다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "La reunión es ( ) el martes.", "정답": "el", "오답": "en,a,de,por", "번역": "회의는 화요일*에* 있다.", "유형": "time_point", "해설": "요일 앞에는 'el'을 씁니다."},
    {"문장": "Nací ( ) mayo.", "정답": "en", "오답": "a,de,por,para", "번역": "나는 5월*에* 태어났다.", "유형": "time_point", "해설": "월 앞에는 'en'을 씁니다."},
    {"문장": "Vivo ( ) el tercer piso.", "정답": "en", "오답": "a,de,por,para", "번역": "나는 3층*에* 산다.", "유형": "loc_position", "해설": "층수 앞에는 'en'을 씁니다."},
    {"문장": "El gato está ( ) el sofá.", "정답": "sobre", "오답": "bajo,entre,hacia,desde", "번역": "고양이는 소파 *위에* 있다.", "유형": "loc_position", "해설": "위는 'sobre'입니다."},
    {"문장": "La farmacia está ( ) la derecha.", "정답": "a", "오답": "en,de,por,para", "번역": "약국은 오른쪽*에* 있다.", "유형": "loc_position", "해설": "방향 위치는 'a'입니다."},
    {"문장": "Trabajo ( ) casa.", "정답": "en", "오답": "a,de,por,para", "번역": "나는 집*에서* 일한다.", "유형": "loc_position", "해설": "장소는 'en'입니다."},
    {"문장": "Voy ( ) casa.", "정답": "a", "오답": "en,de,por,para", "번역": "나는 집*으*로 간다.", "유형": "loc_direction", "해설": "목적지는 'a'입니다."},
    {"문장": "Vengo ( ) casa.", "정답": "de", "오답": "a,en,por,para", "번역": "나는 집*에서* 온다.", "유형": "loc_origin", "해설": "출발지는 'de'입니다."},
    {"문장": "El libro es ( ) papel.", "정답": "de", "오답": "en,con,por,para", "번역": "책은 종이*로* 만들어졌다.", "유형": "material", "해설": "재료는 'de'입니다."},
    {"문장": "Hablamos ( ) fútbol.", "정답": "de", "오답": "a,en,por,para", "번역": "우리는 축구*에 대해* 이야기했다.", "유형": "topic", "해설": "주제는 'de'입니다."},
    {"문장": "Gracias ( ) tu regalo.", "정답": "por", "오답": "para,a,de,en", "번역": "네 선물 *고마워*.", "유형": "cause", "해설": "이유는 'por'입니다."},
    {"문장": "Estudio ( ) aprender.", "정답": "para", "오답": "por,a,de,en", "번역": "배우기 *위해* 공부한다.", "유형": "purpose", "해설": "목적은 'para'입니다."},
    {"문장": "Te cambio mi boli ( ) tu lápiz.", "정답": "por", "오답": "para,a,de,en", "번역": "내 볼펜을 네 연필*과* 바꿀게.", "유형": "exchange", "해설": "교환은 'por'입니다."},
    {"문장": "Nos vemos ( ) la mañana.", "정답": "por", "오답": "a,de,en,para", "번역": "아침*에* 보자.", "유형": "time_duration", "해설": "시간대는 'por'입니다."},
    {"문장": "Son las tres ( ) la tarde.", "정답": "de", "오답": "por,a,en,para", "번역": "오후 3시다.", "유형": "time_point", "해설": "구체적 시각 뒤 시간대는 'de'입니다."},
    {"문장": "El regalo es ( ) ti.", "정답": "para", "오답": "por,a,de,en", "번역": "선물은 너*를 위한* 거야.", "유형": "company", "해설": "수혜자는 'para'입니다."},
    {"문장": "Lo hago ( ) ti.", "정답": "por", "오답": "para,a,de,en", "번역": "나는 너 *때문에* 한다.", "유형": "cause", "해설": "원인은 'por'입니다."},
    {"문장": "El tren pasa ( ) el túnel.", "정답": "por", "오답": "para,a,de,en", "번역": "기차는 터널*을* 지나간다.", "유형": "loc_path", "해설": "경로는 'por'입니다."},
    {"문장": "La mesa está ( ) la cocina.", "정답": "en", "오답": "a,de,por,para", "번역": "탁자는 부엌*에* 있다.", "유형": "loc_position", "해설": "위치는 'en'입니다."},
    {"문장": "Voy a ir ( ) pie.", "정답": "a", "오답": "en,por,con,de", "번역": "*걸어서* 갈 것이다.", "유형": "method", "해설": "수단은 'a'입니다."},
    {"문장": "Estoy ( ) viaje.", "정답": "de", "오답": "en,a,por,para", "번역": "나는 여행 *중*이다.", "유형": "manner", "해설": "상태는 'de'입니다."}
]

output_path = 'src/data/preposition_quiz.csv'
headers = ['문장', '뜻', '정답', '오답', '유형', '해설']

with open(output_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=headers, quoting=csv.QUOTE_ALL)
    writer.writeheader()
    for item in quiz_data:
        writer.writerow({
            '문장': item['문장'],
            '뜻': item['번역'],
            '정답': item['정답'],
            '오답': item['오답'],
            '유형': item['유형'],
            '해설': item['해설']
        })

print(f"Successfully generated {len(quiz_data)} manual items in {output_path}")
